# 예외 처리
```java
try {
    예외를 처리하길 원하는 실행 코드;
} catch (e1) {
    e1 예외가 발생할 경우에 실행될 코드;
} catch (e2) {
    e2 예외가 발생할 경우에 실행될 코드;
}
...
finally {
    예외 발생 여부와 상관없이 무조건 실행될 코드;
}
```
- 프로그램 실행 시 발생할 수 있는 예기치 못한 예외의 발생에 대비한 코드를 작성하는 것
- 예외의 발생으로 인한 프로그램의 비정상 종료를 막고 정상적인 실행 상태를 유지
- 발생한 예외를 처리하지 못하면 프로그램은 비정상 종료되며 JVM의 예외처리기(UncaughtExceptionHandler)가 예외의 원인을 화면에 출력
- Exception, Error 클래스는 Throwable 클래스를 상속받았으며, Throwable 클래스도 Object 클래스의 자손 클래스
- RuntimeException 클래스는 개발자의 실수에 의해 발생하는 예외로 구성
    - RuntimeException 클래스를 제외한 Exception 클래스는 사용자들의 동작에 의해 발생하는 예외
- RuntimeException 클래스는 예외처리를 강제 X

# 오류와 예외
```
1. 오루
- 프로그램에 의해 수습될 수 없는 심각한 오류 
- 시스템 레벨에서 프로그램에 심각한 문제를 야기하여 실행 중인 프로그램을 종료
- 개발자가 미리 예측하여 처리할 수 없는 것이 대부분이므로 오류에 대한 처리 불가

2. 예외
- 프로그램 코드에 의해 수습될 수 있는 다소 미약한 오류
- 실행 중인 프로그램을 비정상적으로 종료시키지만, 발생할 수 있는 상황을 미리 예측하여 처리
```

# 예외 처리 메커니즘
```
1. try 블록에 도달한 프로그램의 제어는 try 블록 내의 코드를 실행
- 이때 만약 예외가 발생(throw)하지 않고, finally 블록이 존재하면 프로그램의 제어는 바로 finally 블록으로 이동합니다.
2. try 블록에서 예외가 발생하면 catch 핸들러는 다음과 같은 순서로 적절한 catch 블록을 탐색
   2-1. 스택에서 try 블록과 가장 가까운 catch 블록부터 차례대로 검사
   2-2. 만약 적절한 catch 블록을 찾지 못하면, 바로 다음 바깥쪽 try 블록 다음에 위치한 catch 블록을 차례대로 검사
   2-3. 이러한 과정을 가장 바깥쪽 try 블록까지 계속 검사
   2-4. 그래도 적절한 catch 블록을 찾지 못하면, 예외는 처리 불가
3. 만약 적절한 catch 블록을 찾게 되면, throw 문의 피연산자는 예외 객체의 형식 매개변수로 전달
4. 모든 예외 처리가 끝나면 프로그램의 제어는 finally 블록으로 이동
5. finally 블록이 모두 처리되면, 프로그램의 제어는 예외 처리문 바로 다음으로 이동
```

# Try-Catch
- 발생한 예외의 종류와 일치하는 한 개의 catch 블럭만 수행
- 메소드 내에 여러 개의 try-catch문이 사용될 수 있으며 try-catch 블럭에 다른 try-catch문이 포함 가능
- try-catch 블럭 내에 선언된 변수는 catch 블럭 내에서만 유효
- Catch 블럭에서 Exception 클래스로 만들어진 참조변수에 접근 가능
- printStackTrace() : 예외발생 당시의 호출 스택에 있었던 메소드의 정보와 예외 메시지를 화면에 출력
    - 파일에 예외의 정보를 저장 가능
- getMessage() : 발생한 예외클래스의 인스턴스에 저장된 메시지를 반환
- 멀티 catch블럭은 '|'기호를 이용해서 중복된 코드를 줄이는 것이 가능.
    - 연결된 예외 클래스가 상속 관계에 있다면 컴파일 에러 발생
- 멀티 catch 블럭에 연결된 예외 클래스는 공통 분모인 조상 예외 클래스에 선언된 멤버만 사용 가능
- instanceof로 예외의 타입을 확인하고 이에 해당하는 자손 예외 클래스로 형변환하여 자손 예외 클래스의 멤버를 사용 가능

# finally
- 예외의 발생여부에 관계없이 실행되어야할 코드를 포함시킬 목적으로 사용
- try-catch-finally의 순서로 구성
- try-catch 블럭에서 return문이 실행되는 경우에도 finally 블럭의 문장들이 먼저 실행되고 나서 return을 수행
- try 블럭과 finally 블럭에서 모두 예외가 발생하면 try 블럭의 예외는 무시
